### ISSUE TITLE
Can't write model/residual maps for template ROIs

### ISSUE THREAD

**Issue by henrikef** [threeML/hawc_hal#22]
Will add a script to reproduce this later on, but this is the error message when calling `write_model_map` using a template ROI:

Traceback (most recent call last):
  File "/Users/hfleisch/software_base/gitlab_aerie/threeml-analysis-scripts/fitModel/fitModel.py", line 722, in <module>
    like.write_model_map("{1}/{0}_modelMap.{2}".format(name, outdir, suffix))
  File "/Users/hfleisch/miniconda3/envs/st_test3/lib/python2.7/site-packages/hawc_hal/HAL.py", line 942, in write_model_map
    self._write_a_map(file_name, 'model', poisson_fluctuate, test_return_map)
  File "/Users/hfleisch/miniconda3/envs/st_test3/lib/python2.7/site-packages/hawc_hal/HAL.py", line 928, in _write_a_map
    new_map_tree.write(file_name)
  File "/Users/hfleisch/miniconda3/envs/st_test3/lib/python2.7/site-packages/hawc_hal/maptree/map_tree.py", line 191, in write
    serializer.store_pandas_object('/ROI', pd.Series(), **self._roi.to_dict())
  File "/Users/hfleisch/miniconda3/envs/st_test3/lib/python2.7/site-packages/hawc_hal/serialize.py", line 39, in store_pandas_object
    self._store.get_storer(path).attrs.metadata = metadata
  File "/Users/hfleisch/miniconda3/envs/st_test3/lib/python2.7/site-packages/tables/attributeset.py", line 481, in __setattr__
    self._g__setattr(name, value)
  File "/Users/hfleisch/miniconda3/envs/st_test3/lib/python2.7/site-packages/tables/attributeset.py", line 423, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)
  File "tables/hdf5extension.pyx", line 710, in tables.hdf5extension.AttributeSet._g_setattr
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5A.c", line 259, in H5Acreate2
    unable to create attribute
  File "H5Aint.c", line 280, in H5A_create
    unable to create attribute in object header
  File "H5Oattribute.c", line 347, in H5O_attr_create
    unable to create new attribute in header
  File "H5Omessage.c", line 224, in H5O_msg_append_real
    unable to create new message
  File "H5Omessage.c", line 1945, in H5O_msg_alloc
    unable to allocate space for message
  File "H5Oalloc.c", line 1142, in H5O_alloc
    object header message is too large

End of HDF5 error back trace

Can't set attribute 'metadata' in node:
 /ROI (Group) ''.

**Comment by henrikef** [comment]
Fixed in #56
